version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: strava_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strava
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: strava_app
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://user:password@postgres:5432/strava
  #     NEXTAUTH_URL: http://localhost:3000
  #     STRAVA_CLIENT_ID: "ton_client_id"
  #     STRAVA_CLIENT_SECRET: "ton_client_secret"

volumes:
  postgres_data:
